apiVersion: v1
kind: Service
metadata:
  name: dashgen-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.dashgen.webappPort }}
      nodePort: {{ .Values.dashgen.nodePort }}
  selector:
    app: dashgen
