apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashgen-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: dashgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashgen
  template:
    metadata:
      labels:
        app: dashgen
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: dashconfig
        - name: log-volume
          hostPath:
            path: {{ .Values.logger.hostPath }}
        - name: dash-volume
          persistentVolumeClaim:
            claimName: dash-storage

      containers:
        - name: dashgen-webapp
          image: {{ .Values.dashgen.image }}
          command: ["/dashgen"]
          #args: ["$(MYSQL_HOST)", "$(MYSQL_PASSWORD)"]
          ports:
            - containerPort: {{ .Values.dashgen.webappPort }}
          resources:
            requests:
              memory: {{ .Values.dashgen.resources.requests.memory }}
              cpu: {{ .Values.dashgen.resources.requests.cpu }}
            limits:
              memory: {{ .Values.dashgen.resources.limits.memory }}
              cpu: {{ .Values.dashgen.resources.limits.cpu }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: defaultConfig.json
            - name: dash-volume
              mountPath: /dash
          #env:
          #  - name: MYSQL_HOST
          #    value: mysql.default.svc.clusterf.local
          #  - name: MYSQL_PASSWORD
          #    valueFrom:
          #      secretKeyRef:
          #        name: streamingapphelm-mysql # Adjust with the correct secret name
          #        key: mysql-root-password 


        - name: logger
          image: {{ .Values.logger.image }}
          resources:
            requests:
              memory: {{ .Values.logger.resources.requests.memory }}
              cpu: {{ .Values.logger.resources.requests.cpu }}
            limits:
              memory: {{ .Values.logger.resources.limits.memory }}
              cpu: {{ .Values.logger.resources.limits.cpu }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: defaultConfig.json
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
