apiVersion: v1
kind: PersistentVolume
metadata:
  name: dash-storage
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  storageClassName: vmware-sc
  hostPath:
    path: /tmp/pv