apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dash-storage
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: vmware-sc
  volumeName: dash-storage
