apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: {{ .Values.streaming.nodePort }}
  selector:
    app: streaming
