apiVersion: v1
entries:
  example:
  - apiVersion: v2
    appVersion: 1.16.0
    created: '2024-03-15T11:21:09.596971653Z'
    description: A Helm chart for Kubernetes
    digest: 301a58b99de18a00c88d3786da2e5171eafddbae4d8ffc801aed511f45b2a86c
    image_url: https://www.nginx.com/wp-content/uploads/2021/08/NGINX-Part-of-F5-horiz-black-type-1.svg
    name: example
    type: application
    urls:
    - https://github.com/idlab-discover/cnl-packages/releases/download/example-0.1.0/example-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.16.0
    created: '2024-03-15T11:25:10.053122439Z'
    description: Just a prometheus example...
    digest: 3ed6f0597365df55c5e132691ea1459011d35c6888e498af59955fbccfee1c34
    image_url: https://logowik.com/content/uploads/images/prometheus-monitoring-system4911.logowik.com.webp
    name: prometheus
    type: application
    urls:
    - https://github.com/idlab-discover/cnl-packages/releases/download/prometheus-0.1.0/prometheus-0.1.0.tgz
    version: 0.1.0
generated: '2024-03-15T11:25:10.053127719Z'
