apiVersion: v1
entries:
  example:
  - apiVersion: v2
    appVersion: 1.16.0
    created: '2024-03-15T11:21:09.596971653Z'
    description: A Helm chart for Kubernetes
    digest: 301a58b99de18a00c88d3786da2e5171eafddbae4d8ffc801aed511f45b2a86c
    image_url: https://www.nginx.com/wp-content/uploads/2021/08/NGINX-Part-of-F5-horiz-black-type-1.svg
    name: example
    type: application
    urls:
    - https://github.com/idlab-discover/cnl-packages/releases/download/example-0.1.0/example-0.1.0.tgz
    version: 0.1.0
generated: '2024-03-15T11:21:09.596977625Z'
