apiVersion: v1
entries:
  NodeJS:
    - apiVersion: v2
      appVersion: 1.16.0
      created: "2024-03-15T13:47:28.152862587Z"
      description: Newer version of the nodeJS setup.
      digest: 92fa1faaf4d3a4d69e443a57822377daa66de7972639a91f022b3d3e42c6e76e
      image_url: https://default_image.com/image.png
      name: NodeJS
      type: application
      urls:
        - https://github.com/idlab-discover/cnl-packages/releases/download/NodeJS-0.2.0/NodeJS-0.2.0.tgz
      version: 0.2.0
    - apiVersion: v2
      appVersion: 1.16.0
      created: "2024-03-15T13:39:42.370373274Z"
      description: Default NodeJS setup
      digest: bc2e1b778281c9271c77a6782e2dbc931f1a36a487b05efe509e55107dd5e1e8
      image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Node.js_logo_2015.svg/2560px-Node.js_logo_2015.svg.png
      name: NodeJS
      type: application
      urls:
        - https://github.com/idlab-discover/cnl-packages/releases/download/NodeJS-0.1.0/NodeJS-0.1.0.tgz
      version: 0.1.0
  example:
    - apiVersion: v2
      appVersion: 1.16.0
      created: "2024-03-15T11:21:09.596971653Z"
      description: A Helm chart for Kubernetes
      digest: 301a58b99de18a00c88d3786da2e5171eafddbae4d8ffc801aed511f45b2a86c
      name: example
      type: application
      urls:
        - https://github.com/idlab-discover/cnl-packages/releases/download/example-0.1.0/example-0.1.0.tgz
      version: 0.1.0
  prometheus:
    - apiVersion: v2
      appVersion: 1.16.0
      created: "2024-03-15T11:25:10.053122439Z"
      description: Just a prometheus example...
      digest: 3ed6f0597365df55c5e132691ea1459011d35c6888e498af59955fbccfee1c34
      name: prometheus
      type: application
      urls:
        - https://github.com/idlab-discover/cnl-packages/releases/download/prometheus-0.1.0/prometheus-0.1.0.tgz
      version: 0.1.0
generated: "2024-03-15T13:47:28.152875541Z"
