entries:
  kafka-quickstart:
    0.1.0:
      afterInstallationManual: '# What to do after installing?

        This is some example text.

        - list

        - items

        '
      clusterSettings:
        controlPlaneMachineCount: 1
        kubernetesVersion: v1.29.0
        machineCores: 4
        workerMachineCount: 1
        workerMachinesMemory: 8
      imageUrl: https://cloud.ilabt.imec.be/index.php/apps/files_sharing/publicpreview/WQcN47BDdEJT8eG?file=/&fileId=1169654706&x=2560&y=1440&a=true&etag=08edc2516139b7357d06302547b7cb93
    0.1.1:
      afterInstallationManual: '# What to do after installing?

        This is some example text.

        - list

        - items

        '
      clusterSettings:
        controlPlaneMachineCount: 1
        kubernetesVersion: v1.29.0
        machineCores: 4
        workerMachineCount: 1
        workerMachinesMemory: 8
      imageUrl: https://cloud.ilabt.imec.be/index.php/apps/files_sharing/publicpreview/WQcN47BDdEJT8eG?file=/&fileId=1169654706&x=2560&y=1440&a=true&etag=08edc2516139b7357d06302547b7cb93
    0.1.2:
      afterInstallationManual: '# What to do after installing?

        This is some example text.

        - list

        - items

        '
      clusterSettings:
        controlPlaneMachineCount: 1
        kubernetesVersion: v1.29.0
        machineCores: 4
        workerMachineCount: 1
        workerMachinesMemory: 8
      imageUrl: https://cloud.ilabt.imec.be/index.php/apps/files_sharing/publicpreview/WQcN47BDdEJT8eG?file=/&fileId=1169654706&x=2560&y=1440&a=true&etag=08edc2516139b7357d06302547b7cb93
    0.1.3:
      afterInstallationManual: '# What to do after installing?

        This is some example text.

        - list

        - items

        '
      clusterSettings:
        controlPlaneMachineCount: 1
        kubernetesVersion: v1.29.0
        machineCores: 4
        workerMachineCount: 1
        workerMachinesMemory: 8
      imageUrl: https://cloud.ilabt.imec.be/index.php/apps/files_sharing/publicpreview/WQcN47BDdEJT8eG?file=/&fileId=1169654706&x=2560&y=1440&a=true&etag=08edc2516139b7357d06302547b7cb93
  nginx:
    1.0.0:
      imageUrl: https://www.nginx.com/wp-content/uploads/2021/08/NGINX-Part-of-F5-horiz-black-type-1.svg
    1.0.1:
      afterInstallationManual: '# What to do after installing?


        This is some example text.

        - list

        - items'
      imageUrl: https://www.nginx.com/wp-content/uploads/2021/08/NGINX-Part-of-F5-horiz-black-type-1.svg
    1.0.2:
      afterInstallationManual: '## What to do after installing?


        This application is exposed using NodePort, to get the IP adress and the port
        of the application run following commands in terminal.

        Make sure your Kubeconfig is correctly exported for this.



        ```bash

        #NodeIP:

        kubectl describe node | grep Addresses: -A 4


        #NodePort:

        kubectl get svc

        ```'
      imageUrl: https://www.nginx.com/wp-content/uploads/2021/08/NGINX-Part-of-F5-horiz-black-type-1.svg
    1.0.3:
      afterInstallationManual: '## What to do after installing?


        This application is exposed using NodePort, to get the IP adress and the port
        of the application run following commands in terminal.

        Make sure your Kubeconfig is correctly exported for this.



        ```bash

        #NodeIP:

        kubectl describe node | grep Addresses: -A 4


        #NodePort:

        kubectl get svc

        ```'
      imageUrl: https://i.imgur.com/JoeEPEP.jpeg
  streaming:
    0.2.0:
      imageUrl: https://variety.com/wp-content/uploads/2022/10/featured_Dare_to_Stream_SR_v6.jpg?w=910&h=511&crop=1&resize=910%2C511
    0.3.0:
      imageUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Microsoft_Stream.svg/1024px-Microsoft_Stream.svg.png
