entries:
  NodeJS:
    0.1.0:
      image_url: Another one
    0.2.0:
      image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Node.js_logo_2015.svg/2560px-Node.js_logo_2015.svg.png
  example:
    0.1.0:
      image_url: https://www.nginx.com/wp-content/uploads/2021/08/NGINX-Part-of-F5-horiz-black-type-1.svg
      something: else
    0.2.0:
      cluster_settings:
        control_plane_machines: 2
        machine_cores: 3
        version: v1.24.10
        worker_machines: 2
        worker_machines_memory: 8
      image_url: https://miro.medium.com/v2/resize:fit:720/format:webp/0*mjG1YdoT7xPcnznN.jpg
  prometheus:
    0.1.0:
      image_url: https://logowik.com/content/uploads/images/prometheus-monitoring-system4911.logowik.com.webp
