kafka:
  namespaceOverride: kafka
  enabled: true
argo-cd:
  namespaceOverride: argocd
  enabled: true
monitoring:
  namespaceOverride: monitoring
  enabled: true
kube-prometheus-stack:
  namespaceOverride: monitoring
  podMonitorSelector:
      matchLabels:
        app: strimzi
  additionalScrapeConfigsSecret: 
        name: additional-scrape-configs
        key: prometheus-additional.yaml
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
  grafana:
    enabled: false
  kube-state-metrics:
    namespaceOverride: monitoring
  prometheus-node-exporter:
    namespaceOverride: monitoring
grafana-operator:
  namespaceOverride: monitoring