namespace: k8slabo

dashgen:
  image: gitlab.ilabt.imec.be:4567/togoetha/sysmgmt/dashgen
  webappPort: 8080
  resources:
    requests:
      memory: "500Mi"
      cpu: "2000m"
    limits:
      memory: "1000Mi"
      cpu: "3000m"
  nodePort: 30080

logger:
  image: gitlab.ilabt.imec.be:4567/togoetha/sysmgmt/logservice
  logPort: 8081
  resources:
    requests:
      memory: "20Mi"
      cpu: "50m"
    limits:
      memory: "50Mi"
      cpu: "100m"
  hostPath: /var/log/myapp/logs

streaming:
  image: gitlab.ilabt.imec.be:4567/togoetha/sysmgmt/httpd
  nodePort: 30081
  resources:
    requests:
      memory: "300Mi"
      cpu: "500m"
  replicas: 2

autoscaler:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilization: "200Mi"
# MySQL values go here if you include the MySQL chart as a dependency.

mysql:
  primary:
    persistence:
      size: "2Gi" # Set the size to 2GB as you wanted
