apiVersion: v1
kind: Service
metadata:
  name: { { include "hello-nginx.fullname" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 80
  selector:
    app.kubernetes.io/name: { { include "hello-nginx.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
