image_url: "https://miro.medium.com/v2/resize:fit:720/format:webp/0*mjG1YdoT7xPcnznN.jpg"
cluster_settings:
  version: "v1.24.10"
  control_plane_machines: 2
  worker_machines: 2
  worker_machines_memory: 8
  machine_cores: 3
