# Create Service Account for diktyo-scheduler
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scheduler.name }}
  namespace: {{ .Release.Namespace }}
---
# Create Service Account for scheduler plugins controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
---
# Create Service Account for NetworkTopology Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.networkTopologyController.name }}
  namespace: {{ .Release.Namespace }}
---
# Create Service Account for AppGroup Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appGroupController.name }}
  namespace: {{ .Release.Namespace }}
---
