apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: strimzi
  namespace: {{ template "monitoring.namespace" . }}
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 32000  # Port for demo purposes
  selector:
    name: grafana
  type: NodePort