apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
  namespace: {{ template "monitoring.namespace" . }}
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: root
      admin_password: secret
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafana-ds-prometheus
  namespace: {{ template "monitoring.namespace" . }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    access: proxy
    type: prometheus
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: prom1
    type: prometheus
    url: http://prometheus-operated:9090
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dashboard-kafka-exporter
  namespace: {{ template "monitoring.namespace" . }}
spec:
  resyncPeriod: 30s
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "prom1"
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  url: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/heads/main/examples/metrics/grafana-dashboards/strimzi-kafka-exporter.json