name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          path: "main"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: "gh-pages"

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.yaml
          git commit -m "Update index.yaml with custom fields from site.yaml"
          git push origin gh-pages

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install PyYAML

      - name: Copy index.yaml to site.yaml
        run: cp ./gh-pages/index.yaml ./gh-pages/site.yaml

      - name: Run script to update site.yaml with custom values
        run: |
          python3 ./main/add_additional_info.py
        env:
          CHARTS_DIR: "./main/charts"
          SITE_FILE: "./gh-pages/site.yaml" # Notice we're now pointing to site.yaml

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add site.yaml
          git commit -m "Update site.yaml with custom fields"
          git push origin gh-pages
